### ISSUE TITLE
Footer padding

### ISSUE THREAD

**Issue by Gem-Hactar** [openownership/openownership.org-wagtail#172]
Needs space between wording in footer

safari 14.0.3

<img width="1064" alt="Screenshot 2022-04-19 at 14 31 29" src="https://user-images.githubusercontent.com/64021485/164015737-8bde2126-231f-4b8b-b8c9-4c2dbf8e4369.png">

**Comment by ohhelloana** [comment]
@Gem-Hactar this seems to be fixed already. Can you please check and see if you're happy with the current spacing?
