### ISSUE TITLE
Expiring jobs pages once the application deadline has passed

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#348]
In our initial Wagtail v2 setup for the Open Ownership website, there was an expiration date field for Job pages. When set, this would remove the pages from the live site after the application date had passed.

In our current Wagtail v4 setup, we are keen to use this same functionality but are unsure how to do so. There is an Application deadline field on the Content tab for each job page:
<img width="831" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/66c62d93-8c35-4046-9c50-db6ad0f8a1ab">

And we can see in the CMS that job pages are given an Expired label once this Application deadline has passed:
<img width="480" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/24a5b9e2-6ad0-48f6-a137-9081f608d13c">

However at the moment this expiration doesn't result in any changes on the job page. So the Open Ownership team is manually unpublishing job ads the day after the application deadline has passed.

The functionality we would like to see is for job pages to automatically be unpublished/moved to draft two days after the application deadline as most of our application deadlines are one minute to midnight at the very end of the application date given on the job pages. Is that possible in Wagtail 4?

**Comment by philgyford** [comment]
@StephenAbbott I just recalled – this should already be possible in Wagtail.

When editing a page:

1. Click the "I" at top-right to view the page's Status
2. Click "Set Schedule"
3. You can set an Expiry date/time

Expired pages will be set to a Status of Draft.

Assuming setting a "Go live date/time" already works, the expiry time should work too. I'm not sure if you already use the "Go live date/time"?

**Comment by StephenAbbott** [comment]
Aha. Did not know this functionality already existed. Will get my colleagues to test it. Thanks @philgyford

**Comment by StephenAbbott** [comment]
@philgyford So we've tested the Set Schedule and Expiry date/time functionality with a couple of pages this week on the staging site and nothing changed after the expiry date/time had passed https://openownership.hactar.work/admin/pages/589/edit/

**Comment by philgyford** [comment]
@drcongo Can you check that the `publish_scheduled` management command is running regularly on Staging? I think that's the thing that should make this happen?

**Comment by StephenAbbott** [comment]
Based on testing carried out by Open Ownership communications team in November 2023, this page expiry functionality is working as expected so I'll close the ticket
