### ISSUE TITLE
Create region pages to show descriptions of the work Open Ownership is doing

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#350]
Once work has been done to add an additional rich text description field to country pages in the OO Wagtail CMS (see https://github.com/openownership/openownership.org-wagtail/issues/349), we would like to create regional summary pages which pull from existing Notion fields to give a quick overview of the work Open Ownership is doing across the world.

Separate region pages should be created for each of the regions we have in the existing CMS:

- Africa
- Asia
- Europe
- North America
- Oceania
- South America

Following the URL pattern set for the Open Ownership Map and underlying country pages, the URL for each of these regional pages should be openownership.org/en/map/region/NAMEOFREGION

The region page could follow the Tag page layout/design and should display a list of countries where the country has the region ticked in the Regions list and also has something in the OO Support field from Notion. Countries where OO Support is blank should not be displayed.

For each country belonging to that region where OO Support is filled in, the name of the country should be displayed on the region page which should link to the country page URL. Under the name of the country, the rich text description field should be displayed which summarises the nature of OO's current support to the country (see https://github.com/openownership/openownership.org-wagtail/issues/349).

It would also be useful for the Open Ownership team to be able to add an optional blurb/description text field at the top of the page under the region name to explain the information showing up on the page.

Open Ownership and Hactar should discuss how best to flag the existence of these regional pages from the [Open Ownership map page](https://www.openownership.org/en/map/). Perhaps a new section should be added under 'Find a specific country' entitled 'Learn more about Open Ownership's work' followed by links to all the regional pages? 

Or would this be confusing for users as it may look like it duplicates both the text and the accordion functionality of the 'Find a specific country' section? Advice welcome...

**Comment by StephenAbbott** [comment]
Ideas from team discussions about how to link to the region pages:

- At the very top of the list of countries that appears within a region (so above 'Albania' for Europe), we have text which reads: Read a regional summary of Europe here
- Alternatively, the word 'Europe' itself is hyperlinked to the regional descriptor page, but for that to be obvious to users, we would need to add text within its field, so it reads something like 'Europe - regional summary'

To discuss further...

**Comment by StephenAbbott** [comment]
Recommendation from Gemma:

> My recommendation would be to have light-touch region pages where you can talk about the team, add their contact and a ‘latest from’ that team/region, but don’t go too deep on content so it’s not silo’d and reflecting internal structures. You want to keep your work as ‘work of OO’ as a whole. We can also put a block on any page that says ‘this is by this region team’ and link through to that team’s about page.

**Comment by philgyford** [comment]
Breaking down what I need to do for this:

- [ ] Create Region pages (follow roughly how it's done in `modules.content.views.CountryView`)
  -  URLs like `openownership.org/en/map/region/NAMEOFREGION`
  - Display a list of countries in that region, linking to country pages.
    - Only include countries "where the country has the region ticked in the Regions list and also has something in the OO Support field from Notion".
    - Under country name display existing rich text description field. 
- [ ] Add optional description text field to Region and display on Region page under name.
- [ ] TBD: How to link to these pages from Map Page

**Comment by philgyford** [comment]
@StephenAbbott Dumb question, but I'm a bit rusty on some of the basics of this project – when you say "The region page could follow the Tag page layout/design" can you give me an example of what you mean by a "Tag page"?

**Comment by StephenAbbott** [comment]
@philgyford Here are some tag pages:
https://www.openownership.org/en/principles/verification/
https://www.openownership.org/en/topics/beneficial-ownership-data-standard/

**Comment by philgyford** [comment]
On the `350-region-pages` branch, the backend is working and generates pages like this at URLs like `/en/map/region/europe/`:

<img width="1177" alt="Screenshot 2023-09-07 at 13 57 18" src="https://github.com/openownership/openownership.org-wagtail/assets/66670/b916cdf3-5e76-4bee-bc71-879f6cdab837">

**Comment by StephenAbbott** [comment]
@philgyford @ohhelloana Great to see the region pages on our staging website: https://openownership.hactar.work/en/map/region/africa/

Issue to raise: the description text next to each country's name is pulling in text from the 'Blurb' field from the Notion country details in Wagtail - but we actually want to pull in text from the new 'Open Ownership Ongoing Work Body' field which was added as part of https://github.com/openownership/openownership.org-wagtail/issues/349 cc @HollieWilmot

**Comment by HollieWilmot** [comment]
Thanks Stephen! I've just been testing the map, country and region pages myself this morning so there are a couple of things to fix. 

I'm glad you've raised that issue, as I had on my list: Question for Stephen:  It feels repetitive saying ‘ Find details about <countries> commitments to and implementation of beneficial ownership transparency reforms.  So that solves that!

**Comment by HollieWilmot** [comment]
Hi Stephen, I've sent updates on the map and country pages. The update for the region page will be a task for @philgyford  when he's back in on 6th so I've assigned this ticket over to him for now.

**Comment by StephenAbbott** [comment]
Thanks @HollieWilmot

**Comment by HollieWilmot** [comment]
Second task for Phil on region pages: Show **no text** next to the country name if the OOO Work Body field is not filled in.

**Comment by philgyford** [comment]
I've done that (just pending being moved to staging).

I was slightly confused by the "two" tasks though, so hopefully I've done what's required.

It was showing the `blurb` for each country, if it had one.

Now it's showing the `oo_ongoing_work_body` for each country, if it has one.

I'm not clear why "Show **no text** next to the country name if the OOO Work Body field is not filled in." is a second task - it already wasn't showing anything if `blurb` (and now `oo_ongoing_work_body`) wasn't filled in.

**Comment by HollieWilmot** [comment]
This update is now live on staging to check @StephenAbbott. I had a look and it seems like only Kenya has some blurb. Does that seem right?

**Comment by StephenAbbott** [comment]
@HollieWilmot Yep. I've only added the Kenyan blurb in the staging version of the Notion country editing section so that sounds right to me.

We've got a lot more blurbs in production (see examples below):
https://www.openownership.org/en/map/country/united-kingdom-of-great-britain-and-northern-ireland/
https://www.openownership.org/en/map/country/nigeria/

**Comment by StephenAbbott** [comment]
Signed off ✅
