### ISSUE TITLE
Bug: Black cross image appearing instead of Open Ownership logo when homepage loads

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#351]
Several times recently, internal users of the OO website have reported that - upon loading the homepage - a large black cross has appeared in the top left-hand corner of the page instead of the OO logo. As the page loads, this image is then replaced by the normal OO logo. The black cross is just visible for a second or two. Is there a reason for this? And could we do something to mitigate the issue?

**Comment by StephenAbbott** [comment]
Here is a video of the bug:
https://github.com/openownership/openownership.org-wagtail/assets/1506468/247327fc-27ce-47c1-9779-f717f82e2384

**Comment by ohhelloana** [comment]
Hi @StephenAbbott - I've had a look at our code base we don't seem to have anything similar to that. I've throttled my internet speed to see a slow load and I can't seem to reproduce it either. 

I suppose this is on chrome, what browser extensions do people have on when they experience this? Does this happen in incognito mode or in any other browsers? 

Thanks!!

**Comment by StephenAbbott** [comment]
@ohhelloana Hi Ana. Hmmmm. I've experienced this bug a couple of times myself. 

I'm using Chrome Version 113.0.5672.126. And here are the extensions I have installed
<img width="1282" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/e5ca6722-b06f-453f-941d-049254e3f799">

I've seen this in normal and not incognito mode but haven't done extensive testing

**Comment by ohhelloana** [comment]
I still haven't been able to reproduce this which is frustrating. The only extension I wasn't able to install was the "Page Reader" (bottom left) - I wasn't able to find it in the chrome extension store. 

I will keep an eye on it and do more testing but my gut is telling me that it something external causing it.

**Comment by Gem-Hactar** [comment]
@StephenAbbott Have you only heard of this issue from OO people? As Ana said, if we can't reproduce it, it's likely an internal issue. Sonny says it might be a security feature in your network or a cache. Basically, there night be something in your network quickly checking the site before it loads it.

I've opened the site and don't see it, using Safari and Chrome.

Can I recommend you send a test out to people in OO, and then some not in OO (friends will do) and record who sees it and who doesn't?

**Comment by philgyford** [comment]
The "Issues found0" was the clue… it's the Wagtail user bar – the round circle that appears at lower right when you're signed in.

Opening it, and selecting "Accessibility", the pop-up looks like:

<img width="642" alt="Screenshot 2023-08-14 at 17 43 29" src="https://github.com/openownership/openownership.org-wagtail/assets/66670/aa9146f4-ef60-42d1-bb42-6ca1c6fd8b46">

"Issues found 0" and a close icon.

So, while it's not ideal, it looks like this is HTML in the page that's appearing before other things, including the CSS/JS that hides it, has loaded. And it will only appear for users who are signed in to Wagtail.

**Comment by StephenAbbott** [comment]
Aha. Clever. Thanks @philgyford. That's a relief to know. I'll communicate this to the team
