### ISSUE TITLE
Remove Share buttons from utility page template and make utility pages full-width on desktop

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#372]
Pages like the [Terms](https://www.openownership.org/en/terms/) and [Privacy](https://www.openownership.org/en/privacy/) pages on the Open Ownership website use the utility page template in Wagtail.

The share buttons which take up the right-hand column on these pages are redundant and we'd like to introduce the ability to remove them. 

Alongside this change, we'd also like for any code blocks added to the body field of utility pages to display across the full width of the utility page when viewed on desktop

**Comment by philgyford** [comment]
@StephenAbbott Can you let me know how you're adding code blocks to the body field? I can't see a specific code block so maybe you're using Raw HTML? I want to make sure I'm working with whatever content you'll actually use. Thanks!

**Comment by StephenAbbott** [comment]
Hi @philgyford. Good to see you round these parts again. Hope all is well.

Apologies. When I said "code blocks" above, I was meaning to refer to the Rich text / Embed / Table / Raw HTML / etc... blocks that you can add to any body section using the existing Wagtail tools:
<img width="386" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/756ee96f-2843-4ff8-9d95-c476541ced60">

We definitely plan to use the Raw HTML block on utility pages going forward if that helps at all. I'm not sure whether we have tested its use on utility pages before.

**Comment by philgyford** [comment]
Ah sorry, crossed wires – I thought you meant blocks containing code!

So, if there are no sharing buttons, you'd want a Utility page to look as if there's no right-hand column at all? Looking something like this?

<img width="1399" alt="Screenshot 2023-08-14 at 12 26 17" src="https://github.com/openownership/openownership.org-wagtail/assets/66670/fba854db-981b-46fe-b2b3-45b7da246277">

It does make the lines rather long and harder to read I think?

(All good here thanks! Nice to be back temporarily.)

**Comment by StephenAbbott** [comment]
@philgyford Yes exactly. We'd want a Utility page to look as if there's no right-hand column at all.

Appreciate your warning about making the lines long when these pages are viewed on desktop (right-hand column hidden on mobile anyway), but I think it will be OK. 

I believe the template is only used for our Terms and Privacy pages but we are planning on adding a new utility page with some embedded graphics/interactive visuals.

**Comment by philgyford** [comment]
@StephenAbbott I haven't thought much about how to do this, but one alternative might be to keep the body text the current width but, on utility pages, allow certain elements – like images and tables - be the full width. Here's how it would look for a table, for example:

<img width="1442" alt="Screenshot 2023-08-14 at 13 46 24" src="https://github.com/openownership/openownership.org-wagtail/assets/66670/064d9a8b-041d-4636-9108-4f6dbe5d1567">

That'd keep the text to readable length but allow wider things as much space as possible.

**Comment by StephenAbbott** [comment]
@philgyford Have consulted with colleagues who agree with you that keeping the body text the current width but, on utility pages, allowing elements like images and tables to be full width is the best approach here.

I think the following elements should be full width:
- Embed
- Table
- Image
- Raw HTML

based on the feeling that Rich text, Pull quote, Summary/highlight box, Link and Details are all text-focused elements.

How does this sound to you?

**Comment by philgyford** [comment]
@StephenAbbott Sounds good - I'll see what I can do and let you know if there are any difficulties with any of those.

One thing I should have thought of before: It would simpler (in terms of reducing the number of varying template possibilities) if we made it so that Utility Pages never have sharing buttons. So, there wouldn't be a switch to turn them off/on – if you're making a Utility Page there would never be sharing buttons, and Embed, Table, etc would always be full width. Does that sound OK?

**Comment by StephenAbbott** [comment]
Yes. That's great. No need for sharing buttons

**Comment by StephenAbbott** [comment]
Signed off ✅
