### ISSUE TITLE
BUG: Search button being cut off on desktop and mobile browsers

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#384]
Bug spotted today where the purple 'Search' button at the top of the search page on Open Ownership website is being cut off.

Same behaviour observed across desktop Chrome/Firefox browsers and mobile Chrone/Firefox browsers.

Desktop:
<img width="1025" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/16caf28f-a44e-4110-8952-25ab12a4e7eb">

Mobile:
![IMG_7537](https://github.com/openownership/openownership.org-wagtail/assets/1506468/7f0306ce-3c07-4684-9663-02b7e9d051a0)

Original designs - see [Sketch link](https://www.sketch.com/s/ddca6779-1055-4051-b7d6-ec699057b3e6/a/xrvqw9l) - show how the full purple search button is supposed to be shown:
<img width="1007" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/63b0d36a-38c6-4f45-a1f7-c56a69bf2199">

The search functionality still works when you enter a search term and click on the small visible bit of the purple button, but button should be fixed ASAP.

**Comment by philgyford** [comment]
@ohhelloana Looks like this is because the button's contents are hidden:

```html
        <button class="btn" type="submit">
          <span class="visually-hidden">{% trans %}Search{% endtrans %}</span>
        </button>
```

Which looks deliberate so I'm wondering if there's something else not working here, or if it's safe to just remove the `<span>` and leave the text?

**Comment by StephenAbbott** [comment]
Signed off ✅
