### ISSUE TITLE
Update Notion logic/filtering options for the Open Ownership Map

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#396]
As of August 2023, the [Open Ownership Map](https://www.openownership.org/en/map/) (OO Map) is focused on communicating which countries have committed to a central beneficial ownership register or a public register alongside details about whether those countries have gone on to actually implement said central or public registers.

When you land on the OO Map, you see a colour-coded view of all countries showing whether they have made commitments to have a central and/or a public register. Once a user clicks on the Implementation of BOT box below the OO Map, the view then changes to showing whether countries have implemented central and/or public registers:
<img width="555" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/d201d65a-67b3-4e6b-a474-b0f390074fd4">

The focus of the Open Ownership/Hactar tech sprint taking place in September 2023 is to move away from this central/public binary but to still use data from our integrated Notion databases to categorise countries on the OO Map.

The future categories we would like to move to are:
- Planned
- Implementing
- Live register

Our initial thoughts about how to use Notion fields to categorise all countries are below:
- If a country has no commitments in the commitment tracker or implementation details in the implementation tracker, it will not be added to one of the categories
- If a country only has commitments in the commitment tracker, it will be in the `Planned` category
- If a country has any entries in the implementation tracker where the stage is not publish, then it will be in the `Implementing` category
- If a country has any entries in the implementation tracker where the stage is publish, then it will be in the `Live register` category

Countries should only ever appear in one category (or in no category at all if they do not fulfil any of the requirements set out above).

Underneath the OO Map, we plan to remove the Commitment to BOT and Implementation of BOT boxes but would like to retain the ability to count the number of countries in each of the three categories - Planned / Implementing / Live register. 

We would like to display the titles of these categories below the OO Map with a count next to each category title setting out the number of countries which currently belong in that category. 

Clicking on a category name should filter the OO Map to just show countries in that category but when the OO Map page first loads, it should show colour code the categories so that all countries which are in either one of the Planned / Implementing / Live register categories are marked as such.

Once this Notion work is completed, we'd like to request work to 'Update design for the Open Ownership Map' (see https://github.com/openownership/openownership.org-wagtail/issues/397) and also to 'Update download country data functionality for OO Map and country pages' (see https://github.com/openownership/openownership.org-wagtail/issues/399).

**Comment by StephenAbbott** [comment]
@philgyford It should be option 2. I think everything is already there in the Notion data but we just want to interpret it into different categories

**Comment by philgyford** [comment]
@StephenAbbott Do you have any thoughts on what the initial state of the map should be, once we remove the Commitment/Implementation boxes? The current map's initial state is as if you'd just pressed the "Commitment to BOT" box.

I think the options are to default to one of the three new categories being selected, or else none of them, which would leave all the countries pale blue with no shading.

**Comment by StephenAbbott** [comment]
@philgyford If countries can only be in one of the three categories or blank, then it would be good if   design allows for the initial state of map to colour each country in line with its category. 

Then users could click the category names below the map to highlight just countries in that particular category

**Comment by philgyford** [comment]
@StephenAbbott Oh, the other option of course is that all three are selected!

**Comment by philgyford** [comment]
@StephenAbbott Sorry, missed your comment. Yes, so initially all categories are selected.

Then clicking a category will disable the other two and leave only that one category selected.

**Comment by StephenAbbott** [comment]
Yup exactly

**Comment by StephenAbbott** [comment]
@philgyford Flagging that we are shortly planning to make some changes to the internal databases/trackers which Notion pulls information from for the website. 

There's a chance that this will affect some of the fields being used here and so we should set aside some testing after those changes are made.

I will liaise with my colleagues on this and keep you posted by sharing additional info ASAP.

**Comment by StephenAbbott** [comment]
Signed off ✅
