### ISSUE TITLE
Update design for Open Ownership country pages

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#398]
The Open Ownership country pages display a large amount of the information that Open Ownership holds in our internal Notion databases on the state of beneficial ownership transparency in a particular country. They also display content tagged to that country which Open Ownership has published.

NB: The country pages are not created as normal Wagtail pages at present as they mainly draw information from Notion. This should be taken into account if we want to make design changes as it may be more difficult to - for example - add child pages in Wagtail under a main country page if the country page is not a full Wagtail page.

As part of our work to 'Update design for the Open Ownership Map' (see https://github.com/openownership/openownership.org-wagtail/issues/397), we would like to do a small redesign and reorganisation of the information shown on the Open Ownership country pages. Below is a list of the new changes we'd like to see as well as the existing functionality we'd like to retain:

**New functionality requests**

- [x] Remove 'Commitment to one or more' and 'Implemented one or more' BOT information boxes
- [x] Replace information boxes with category label from OO Map page to show if a country is at the Planned / Implementing / Live register stage (all countries should only be in one category). This should use the same design as the OO Map page
- [x] Add a brief text field for OO team members to explain what the categories mean
- [x] If a country is in the 'Live register' category, show list of all register names for that country pulled from Notion (similar to the current functionality which shows these names in the 'Implemented one or more' boxes). Where there is a URL for those registers, link the name to that URL as currently happens. In some cases, countries will have more than one register (see [UK](https://www.openownership.org/en/map/country/united-kingdom-of-great-britain-and-northern-ireland/) or [Nigeria](https://www.openownership.org/en/map/country/nigeria/) country pages for example). Consider how best to display this information in design alongside the Planned / Implementing / Live register stage information
- [x] Remove large flag image or display a smaller version as part of updated design
- [x] Reorder detail sections so the Implementation details appear above Commitment details
- [x] Add ‘Show further detail’ button to Commitment details section so that commitments are hidden by default but can be exposed
- [ ] If useful, consider removing left-hand navigation Impact section navigation links and replacing with internal/anchor tags to link to sections of the country page

**Existing functionality to retain**

- [x] Make sure to still display 'Relevant articles and publications' section with pagination which shows all Open Ownership content tagged to that country. If possible, look to make this more prominent or display it higher up the page
- [x] Retain [optional rich text field](https://github.com/openownership/openownership.org-wagtail/issues/349) work in future country page design, making sure to factor this in so that it appears on country pages when filled in as well as appearing on future region pages (see https://github.com/openownership/openownership.org-wagtail/issues/350)
- [x] Show blurb text field 
- [x] Show when records last updated
- [x] Show contact person for country
- [x] Continue to offer [Download country data](https://www.openownership.org/en/map/country/nigeria.csv) functionality
- [x] Continue to show 'Data is drawn from publicly-available sources and may not be comprehensive for all countries. If data is incorrect, [please let us know](https://share.hsforms.com/1ooDVGfPWQFyc93l3Bds9jA3upv4).' button

**Comment by philgyford** [comment]
@ohhelloana I added a bit at the top of `country.jinja` demonstrating how to use the new `country.category` and `country.category_display` fields that will be needed for this page. You can't miss it :) Shout if you need more info.

**Comment by HollieWilmot** [comment]
@ohhelloana as discussed, please render table rather than have it hideable under show further detail. 

Commitment details text to be hidden on first load behind the 'Show further detail' button.

**Comment by HollieWilmot** [comment]
Internal Testing feedback @StephenAbbott fyi

- We’re missing the text to explain what the category means 
- Contact Person should be Consultants details
- Reduce size of the flag image to reflect design 

Hollie to check with @StephenAbbott: What should we display in cases where the country doesn’t fall under any category i.e https://openownership.hactar.work/en/map/country/tonga/

**Comment by StephenAbbott** [comment]
@HollieWilmot

- Text to explain individual categories: if a country = Planned, display 'Once a country makes at least a commitment to beneficial ownership transparency, it is at Planned stage'. If country = Implementing, display 'After work starts on implementing a register, a country is in the Implementing stage'. If country = Live register, display 'Following the launch of one or more beneficial ownership registers, a country is labelled as Live register'

- Contact person is correct text, as per current live OO website country pages. Please don't change this to Consultants details

For countries like Tonga which are not in the Planned, Implementing or Live register categories, can we hide the white categories/details box on the country pages? If not and we need to display something, could we display the following text 'This country has not made any commitments relating to beneficial ownership transparency'.

**Comment by HollieWilmot** [comment]
Thanks Stephen! I've made a note on the designs re 'Consultants details' to disregard.

**Comment by HollieWilmot** [comment]
Hi Stephen, 

The country pages have been updated and are now ready for you to review, examples below: 

Planned: 
https://openownership.hactar.work/en/map/country/peru/

Implementing:
https://openownership.hactar.work/en/map/country/canada/

Live Register:
https://openownership.hactar.work/en/map/country/united-kingdom-of-great-britain-and-northern-ireland/

No Category:
https://openownership.hactar.work/en/map/country/tonga/

**Comment by StephenAbbott** [comment]
@HollieWilmot Thanks Hollie. All of these look great. One tiny text issue (my fault!). Could we add a full stop to the end of the No Category text so that it is 'This country has not made any commitments relating to beneficial ownership transparency.' as all the other explanatory text snippets have full stops and it'll bug me if the no category one doesn't 😄

**Comment by HollieWilmot** [comment]
As discussed on emails we will no longer be changing the left hand nav on the Country pages.

**Comment by HollieWilmot** [comment]
Full stop now added on the end of 'no category' text.

**Comment by StephenAbbott** [comment]
Thanks @ohhelloana and @HollieWilmot

**Comment by StephenAbbott** [comment]
Signed off ✅
