### ISSUE TITLE
Update download country data functionality for OO Map and country pages

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#399]
Once work is done on https://github.com/openownership/openownership.org-wagtail/issues/396, https://github.com/openownership/openownership.org-wagtail/issues/397 and https://github.com/openownership/openownership.org-wagtail/issues/398, we should bear in mind that we still want to retain the functionality - https://github.com/openownership/openownership.org-wagtail/issues/158 - which allows users to download all the data displayed on the Open Ownership Map and all the Notion-stored data shown on the Open Ownership country pages.

If any changes have been made to Notion data being displayed on the OO Map or country pages, we should test the download country data functionality to make sure that it is still operating as expected with all the fields shared as before.

**Comment by philgyford** [comment]
@StephenAbbott Can you clarify whether the changes in #396 – the replacement of Commitment/Implementation with three new categories – constitutes "changes [that will] have been made to Notion data being displayed on the OO Map"? 

i.e. if it does, then I *assume* the current "Type" column should be replaced with a new one (called what?) and each cell in that column can contain one of (I'm guessing):

- Planned
- Implemented
- Live register
- [an empty cell]

Is that right? Are there any other changes that will need to be made to the download data?

**Comment by StephenAbbott** [comment]
@philgyford Thanks Phil. I think your assumption is correct. But we need to differentiate between the csv download for the full OO Map and for the individual country pages.

For the full OO map csv file, we can remove the current Type column which isn't very useful and replace with one called Stage which then shows one of the following options:

- Planned
- Implemented
- Live register
- [an empty cell]

I don't think any further changes will be required. 

For the individual country csv files, I don't think we should make any changes at all.

The 'Type' column makes a lot more sense for these files as it helps to show whether that line of the file refers to a commitment made or a register which has actually been implemented.

It is fine for the country csv files not to have the Planned / Implemented / Live register category listed as this will be displayed on the country page itself.

**Comment by philgyford** [comment]
@StephenAbbott Ah thanks. I hadn't even noticed there were individual Country downloads! That all makes sense.

**Comment by StephenAbbott** [comment]
@philgyford Flagging that we are shortly planning to make some changes to the internal databases/trackers which Notion pulls information from for the website. 

There's a chance that this will affect some of the fields being used here and so we should set aside some testing after those changes are made.

I will liaise with my colleagues on this and keep you posted by sharing additional info ASAP.

**Comment by StephenAbbott** [comment]
Signed off ✅
