### ISSUE TITLE
Introduce ability to add full-width banner image instead of page title on utility page template

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#405]
Building on recent work - see https://github.com/openownership/openownership.org-wagtail/issues/372 - that we've done to alter the functionality of the utility page template, I'd like to request a further change.

We want to use the utility page to publish our annual impact report which is designed using the following style:
[OO Impact Report Webpage.pdf](https://github.com/openownership/openownership.org-wagtail/files/12549730/OO.Impact.Report.Webpage.pdf)

The current utility page template does most of what our team wants it to now that some elements are shown in full-width, but we would like to introduce the ability to add a full-width banner image instead of a page title.

Ideally the full-width banner needs to be an HTML banner, not a static image. This is to maintain accessibility, metadata and mobile responsiveness. It needs to contain the title as an actual H1 tag, not just as part of an image. The other elements shown also would need to be HTML (text, button, jump link, image pressed to right) otherwise they won't function.

All other functionality on the page would be unchanged.

**Comment by philgyford** [comment]
@StephenAbbott So this would need fields for:

- Page title (use the existing field)
- Subtitle (for "2020 - 2023" which is a different size and font to the blurb below)
- Blurb ("Our first ever…", rich text)
- Button (link and its text)
- Text for next to the button ("or read highlights below")
- One image

Does that sound right to you? My instinct is that this should be an entirely new kind of page because it complicates the otherwise simple Utility Page, and I bet there will be other changes required in future for pages like this, that wouldn't be needed on standard Utility Pages.

Obviously, it will also need some Front End work from @ohhelloana.

**Comment by StephenAbbott** [comment]
I've copied @ohhelloana in on an email with the designer who has requested these changes this morning.

He asked whether a new page type would make sense too but I feared this might be too much work. Will leave to you and Ana to decide a way forward if that's OK.

But let me know if/when you need a decision from me

**Comment by philgyford** [comment]
@StephenAbbott The toughest question… any thoughts on what the new type of page should be called? Report Page is the most immediately obvious but given it could be used for other things too, maybe something a little less specific?

And, a Utility Page can be created beneath the Home Page (like Terms and Privacy) or beneath a Section Page. Does that still make sense for this new page type?

**Comment by StephenAbbott** [comment]
@philgyford Feature Page? Full Width Page?

**Comment by philgyford** [comment]
OK, I've added a new Feature Page type with the fields mentioned above in.

It uses `templates/contents/feature_page.jinja` which will need some front end magic for the banner.

The body behaves the same as Utility Page in terms of images etc being full-width.

It's currently on branch `405-feature-page`.

<img width="1264" alt="Screenshot 2023-09-08 at 15 42 19" src="https://github.com/openownership/openownership.org-wagtail/assets/66670/d68519ee-843c-4b68-972a-b0e967539007">

**Comment by StephenAbbott** [comment]
Signed off ✅
