### ISSUE TITLE
Bug: Nigerian register details appearing twice on Nigeria country page

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#409]
The implementation details for 'Federal Republic of Nigeria Persons with Significant Control Register' are being shown twice on the [Nigeria country page](https://www.openownership.org/en/map/country/nigeria/):

<img width="710" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/cbf97f40-6789-4ea8-9fc5-21584f6f971f">

I've checked our internal Notion database and there is only one entry there for this register.

From the Disclosure regimes view - https://www.openownership.org/admin/notion/disclosureregime/?q=nigeria - I can see that there are two entries for this register, one which has been soft deleted and one which hasn't. But both are showing on the live Nigeria country page.

<img width="977" alt="image" src="https://github.com/openownership/openownership.org-wagtail/assets/1506468/f228aff7-e56e-4981-a7c0-863dbd73f95d">

How do we clear this out so that the one which is soft deleted is not showing up?

**Comment by philgyford** [comment]
@StephenAbbott I'd like to get the latest Notion data into my local copy so I can check this better, but when I try to sync the data I get an error telling me about a duplicate of Senegal.

Andy tried to have a look at your Notion data and said that while he can only see one there, if he does Cmd+F in Notion, it says there are two there. Could you have a look and see if you can de-duplicate the Senegals!

**Comment by StephenAbbott** [comment]
Bug has been fixed during latest website updates so closing ticket https://www.openownership.org/en/map/country/nigeria/
