### ISSUE TITLE
2024 changes to information available in OO Map and country page downloadable csv files

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#442]
In 2022/2023, we introduced the ability on the Open Ownership website for users to download csv files containing a subset of the information on beneficial ownership commitments and implementation which Open Ownership collects via Notion trackers that power our Open Ownership Map and country pages.

See https://github.com/openownership/openownership.org-wagtail/issues/158 and https://github.com/openownership/openownership.org-wagtail/issues/399 for previous work

Following discussions with our advocacy and policy/research teams, we'd like to make the following changes to the information published in the global csv file under the OO Map and the country files published on the country pages.

Overall aim is to remove all the fields relating to commitments coming from the commitment tracker and instead focus on details about registers coming from the implementation tracker.

**FIELDS TO BE REMOVED FROM GLOBAL CSV FILE AND COUNTRY CSV FILES**
- [x] Remove 'Available on the OO register' field
- [x] Remove 'Available via API' field
- [x] Remove 'Structured data available' field
- [x] Remove 'Threshold used to determine beneficial ownership' field
- [x] Remove 'Central' field
- [x] Remove 'Public access' field
- [x] Remove 'All sectors' field
- [x] Remove 'Date' field

**UPDATED FIELDS FOR GLOBAL CSV FILE AND COUNTRY CSV FILES**
- [x] Link field is currently pulling in links to commitment URLs. Update to show URL from 'Register URL' field in Implementation tracker instead
- [x] Change 'Name' to 'Name of register'
- [x] Change 'Published as BODS' field to 'Data structured in BODS'

**NEW FIELDS FOR GLOBAL CSV FILE AND COUNTRY CSV FILES**
- [x] Add 'Status' field with Planned / Implementing / Live register to reflect which stage the country is at. This status is currently calculated using the logic laid out in [this issue from 2023](https://github.com/openownership/openownership.org-wagtail/issues/396#issue-1875592435). We'll need to update the Notion > Wagtail integration so that this actually becomes a stored field in the database
- [x] Add 'Responsible agency' field from Implementation tracker
- [x] Add 'Agency type' field from Implementation tracker
- [x] Add 'Who can access' field from Implementation tracker which can contain multiple categories

To better explain what all the fields mean, we would also like to have the following information published in a 'Metadata' tab in the csv: 

Beneficial ownership register information | Metadata
-- | --
Country | Name of the country that holds the beneficial ownership register.
Name of register | Name associated with the sectoral or full-economy beneficial ownership register, either as documented in legislation or as referenced by public authorities. Data does not include subnational registers.
Registrar  | The government department that is mandated by the regulation to hold the BO registry.
Type of agency | Type of government departments that is responsible for maintaining the BO registry. Options include Company registrars, Tax authorities, Financial Intelligence Units, Extractive Industries regulators, among others.
Status | This field relates to the implementation status of the BO register. Can be one of the following:- Planned: The country has publicly committed to implementing a beneficial ownership register (either sectorial or full-economy), but there is no public evidence that the work has started yet.- Implementing: The country is in the process of setting up the legal and technical systems required for a beneficial ownership register, but the information is not yet being collected. e.g. a bill has been drafted.- Live register: There is a register where beneficial ownership information is being collected and stored. Means of accessing the information may vary among data users.
Access | Describes which data users have specific and dedicated access provisions to the BOI contained in the register, based on the legislation:- Registrar (only the authority holding the register can access the information)- General public (this implies anyone can access the information in the register. Being accessible to the general public doesn’t prevent the register to impose a fee or to justify a legitimate interest for accessing the information)- Competent authorities (such as Financial Intelligence Units, investigations and prosecutions departments or drug and organised crime agencies)- Obliged entities (i.e. AML-regulated entities)- Non-obliged entities (i.e. all other businesses, regular businesses)- Civil society (non-government organisations according to the definition of each jurisdiction, media outlets, academia, other).- Non-competent authorities (any government agency that doesn’t have an anti-money laundering mandate, such as procurement agencies)- Foreign competent authorities (FIUs or others from a different jurisdiction to the one holding the register)
Scope | This field describes the scope of the register, meaning the type of corporate vehicles requested to submit information. Options include:- Full economy (covering corporate vehicles registered in the country, and operating in all the sectors of the economy)- Sectorial (covering corporate vehicles registered in the country, operating in a particular sector of the economy, such as procurement, extractives, land or other). For further information, we recommend to consult the regulation which will specify which type of corporate vehicles are required to disclose their information, and what’s the extent of the register.
Register link | URL with a link to the beneficial ownership register or to a location where further information about how to access beneficial ownership information in a country.
Data structured in BODS | Whether a country has decided to structure their BO data under the Beneficial Ownership Data Standard (BODS).

**Comment by drcongo** [comment]
@StephenAbbott One question on this - the .csv file format doesn't have a concept of multiple tabs / sheets within one file so to add the metadata we would either need to have two downloadable files (with links for each on the page), or change to an .xls format which is slightly less accessible as it's a proprietary format and not everyone will have access to Excel. Any preference?

**Comment by StephenAbbott** [comment]
@drcongo I think two downloadable files - one updated regularly and one with static metadata - sounds preferable. And hopefully that is the more straightforward option?
